"""add is_completed to tasks

Revision ID: a1b2c3d4e5f6
Revises: 73143e4d9ec3
Create Date: 2025-01-20 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '73143e4d9ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_completed', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('tasks', 'owner_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'owner_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    op.drop_column('tasks', 'is_completed')
    # ### end Alembic commands ###
